FROM python:3.11-slim
WORKDIR /app
COPY backend /app/backend
COPY config /app/config
RUN pip install --no-cache-dir fastapi uvicorn[standard] pandas numpy matplotlib plotly scikit-learn prometheus-client pyyaml
EXPOSE 8080
CMD ["uvicorn","backend.engine.server:app","--host","0.0.0.0","--port","8080"]

